version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: course-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - chatbot-network

  streamlit-app:
    build: .
    container_name: course-chatbot
    ports:
      - "8501:8501"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - elasticsearch
    networks:
      - chatbot-network
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  elasticsearch_data:

networks:
  chatbot-network:
    driver: bridge

